---
- name: Install common packages
  apt: pkg={{ item }} state=latest
  with_items:
    - bitlbee
    - git-core
    - htop
    - python-apt
    - python-dev
    - python-pip
    - python-pycurl
  sudo: yes

- name: Get offlineimap, notmuch source files
  git:
    repo={{ item.repo }} accept_hostkey=yes
    dest={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/{{ item.name }}
  with_items:
    - { name: offlineimap, repo: 'git://github.com/OfflineIMAP/offlineimap.git' }
    - { name: notmuch, repo: 'git://notmuchmail.org/git/notmuch' }

- name: Install offlineimap dependencies
  apt: pkg=python-sqlite state=latest

- name: Prepare OfflineImap package
  shell: make clean; make
    chdir={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/offlineimap
    creates=/usr/local/bin/offlineimap
  register: offlineimap_installed

- name: Install OfflineImap system-wide
  shell: python setup.py install
    chdir={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/offlineimap
  sudo: yes
  when: offlineimap_installed|changed

- name: Install notmuch dependecies
  apt: pkg={{ item }} state=latest
  with_items:
    - libgmime-2.6-dev
    - libtalloc-dev
    - libxapian-dev
    - python-sphinx
    - zlib1g-dev
  sudo: yes

- name: Prepare notmuch package
  shell: make clean; ./configure --emacslispdir={{ ansible_env.HOME }}/.emacs.d/lisp --emacsetcdir={{ ansible_env.HOME }}/.emacs.d/lisp && make
    chdir={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/notmuch
    creates=/usr/local/bin/notmuch
  register: notmuch_installed

- name: Install notmuch system-wide
  shell: make install
    chdir={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/notmuch
  sudo: yes
  when: notmuch_installed|changed

- name: Configure notmuch
  template:
    src=notmuch-config.j2
    dest={{ ansible_env.HOME }}/.notmuch-config
