---
- name: My sources dir is available
  file:
    dest={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}
    state=directory

# ssh-keyscan repo.or.cz |sudo tee -a /etc/ssh/ssh_known_hosts
- name: Get Conkeror source files
  git:
    repo=git://repo.or.cz/conkeror.git
    dest={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/conkeror

- name: Desktop dir is available
  file:
    dest={{ '%s/.local/share/applications'|format(ansible_env.HOME) }}
    state=directory

- name: Desktop file
  template:
    src=conkeror.desktop.j2
    dest={{ '%s/.local/share/applications/conkeror.desktop'|format(ansible_env.HOME) }}

- name: xdg-utils is available
  apt: pkg=xdg-utils state=latest
  when: ansible_distribution == 'Ubuntu'
  sudo: yes

- name: Make it default application
  command: /usr/bin/xdg-mime default conkeror.desktop x-scheme-handler/{{ item }}
  with_items:
    - http
    - https

#sudo update-alternatives --config x-www-browser
