---
- name: Get Conkeror source files
  git:
    repo=git://repo.or.cz/conkeror.git accept_hostkey=yes
    dest={{ mysrcpath|default('%s/src'|format(ansible_env.HOME)) }}/conkeror

- name: Desktop file
  template:
    src=conkeror.desktop.j2
    dest={{ '%s/.local/share/applications/conkeror.desktop'|format(ansible_env.HOME) }}

- name: xdg-utils is available
  apt: pkg=xdg-utils state=latest
  when: ansible_distribution == 'Ubuntu'
  sudo: yes

- name: Is conkeror my default browser?
  command: /usr/bin/xdg-mime query default x-scheme-handler/http
  changed_when: False
  register: conkeror_default

- name: Lets make it default
  command: /usr/bin/xdg-mime default conkeror.desktop x-scheme-handler/{{ item }}
  with_items:
    - http
    - https
  when: conkeror_default.stdout != 'conkeror.desktop'

#sudo update-alternatives --config x-www-browser
